<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3d67bf175996944eb20650deaaeba814
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'Abraham\\TwitterOAuth\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Abraham\\TwitterOAuth\\' => 
        array (
            0 => __DIR__ . '/..' . '/abraham/twitteroauth/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3d67bf175996944eb20650deaaeba814::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3d67bf175996944eb20650deaaeba814::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
